namespace QuanLyBanHang.GUI
{
    partial class frmChiTietHoaDon
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }

            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        private void InitializeComponent()
        {
            grpThongTin = new GroupBox();
            txtThanhTien = new TextBox();
            labelThanhTien = new Label();
            txtDonGia = new TextBox();
            labelDonGia = new Label();
            txtSoLuong = new TextBox();
            labelSoLuong = new Label();
            txtNgayLap = new TextBox();
            labelNgayLap = new Label();
            txtNhanVien = new TextBox();
            labelNhanVien = new Label();
            txtKhachHang = new TextBox();
            labelKhachHang = new Label();
            txtTenSP = new TextBox();
            labelTenSP = new Label();
            txtMaSP = new TextBox();
            labelMaSP = new Label();
            txtMaHD = new TextBox();
            labelMaHD = new Label();
            txtMaCTHD = new TextBox();
            labelMaCTHD = new Label();
            grpDanhSach = new GroupBox();
            dgvChiTietHoaDon = new DataGridView();
            btnDong = new Button();
            btnXoa = new Button();
            btnLamMoi = new Button();
            btnInHoaDon = new Button();
            btnXemChiTiet = new Button();
            btnQuayLai = new Button();
            btnTimKiem = new Button();
            txtTimKiem = new TextBox();
            labelTimKiem = new Label();
            lblThongBao = new Label();
            grpThongTin.SuspendLayout();
            grpDanhSach.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)dgvChiTietHoaDon).BeginInit();
            SuspendLayout();
            grpThongTin.Controls.Add(txtThanhTien);
            grpThongTin.Controls.Add(labelThanhTien);
            grpThongTin.Controls.Add(txtDonGia);
            grpThongTin.Controls.Add(labelDonGia);
            grpThongTin.Controls.Add(txtSoLuong);
            grpThongTin.Controls.Add(labelSoLuong);
            grpThongTin.Controls.Add(txtNgayLap);
            grpThongTin.Controls.Add(labelNgayLap);
            grpThongTin.Controls.Add(txtNhanVien);
            grpThongTin.Controls.Add(labelNhanVien);
            grpThongTin.Controls.Add(txtKhachHang);
            grpThongTin.Controls.Add(labelKhachHang);
            grpThongTin.Controls.Add(txtTenSP);
            grpThongTin.Controls.Add(labelTenSP);
            grpThongTin.Controls.Add(txtMaSP);
            grpThongTin.Controls.Add(labelMaSP);
            grpThongTin.Controls.Add(txtMaHD);
            grpThongTin.Controls.Add(labelMaHD);
            grpThongTin.Controls.Add(txtMaCTHD);
            grpThongTin.Controls.Add(labelMaCTHD);
            grpThongTin.Location = new Point(18, 18);
            grpThongTin.Name = "grpThongTin";
            grpThongTin.Size = new Size(340, 630);
            grpThongTin.TabIndex = 0;
            grpThongTin.TabStop = false;
            grpThongTin.Text = "Thông tin chi tiết";
            txtThanhTien.Location = new Point(128, 527);
            txtThanhTien.Name = "txtThanhTien";
            txtThanhTien.ReadOnly = true;
            txtThanhTien.Size = new Size(182, 25);
            txtThanhTien.TabIndex = 19;
            labelThanhTien.AutoSize = true;
            labelThanhTien.Location = new Point(24, 530);
            labelThanhTien.Name = "labelThanhTien";
            labelThanhTien.Size = new Size(75, 19);
            labelThanhTien.TabIndex = 18;
            labelThanhTien.Text = "Thành tiền";
            txtDonGia.Location = new Point(128, 474);
            txtDonGia.Name = "txtDonGia";
            txtDonGia.ReadOnly = true;
            txtDonGia.Size = new Size(182, 25);
            txtDonGia.TabIndex = 17;
            labelDonGia.AutoSize = true;
            labelDonGia.Location = new Point(24, 477);
            labelDonGia.Name = "labelDonGia";
            labelDonGia.Size = new Size(58, 19);
            labelDonGia.TabIndex = 16;
            labelDonGia.Text = "Đơn giá";
            txtSoLuong.Location = new Point(128, 421);
            txtSoLuong.Name = "txtSoLuong";
            txtSoLuong.ReadOnly = true;
            txtSoLuong.Size = new Size(182, 25);
            txtSoLuong.TabIndex = 15;
            labelSoLuong.AutoSize = true;
            labelSoLuong.Location = new Point(24, 424);
            labelSoLuong.Name = "labelSoLuong";
            labelSoLuong.Size = new Size(68, 19);
            labelSoLuong.TabIndex = 14;
            labelSoLuong.Text = "Số lượng";
            txtNgayLap.Location = new Point(128, 368);
            txtNgayLap.Name = "txtNgayLap";
            txtNgayLap.ReadOnly = true;
            txtNgayLap.Size = new Size(182, 25);
            txtNgayLap.TabIndex = 13;
            labelNgayLap.AutoSize = true;
            labelNgayLap.Location = new Point(24, 371);
            labelNgayLap.Name = "labelNgayLap";
            labelNgayLap.Size = new Size(64, 19);
            labelNgayLap.TabIndex = 12;
            labelNgayLap.Text = "Ngày lập";
            txtNhanVien.Location = new Point(128, 315);
            txtNhanVien.Name = "txtNhanVien";
            txtNhanVien.ReadOnly = true;
            txtNhanVien.Size = new Size(182, 25);
            txtNhanVien.TabIndex = 11;
            labelNhanVien.AutoSize = true;
            labelNhanVien.Location = new Point(24, 318);
            labelNhanVien.Name = "labelNhanVien";
            labelNhanVien.Size = new Size(73, 19);
            labelNhanVien.TabIndex = 10;
            labelNhanVien.Text = "Nhân viên";
            txtKhachHang.Location = new Point(128, 262);
            txtKhachHang.Name = "txtKhachHang";
            txtKhachHang.ReadOnly = true;
            txtKhachHang.Size = new Size(182, 25);
            txtKhachHang.TabIndex = 9;
            labelKhachHang.AutoSize = true;
            labelKhachHang.Location = new Point(24, 265);
            labelKhachHang.Name = "labelKhachHang";
            labelKhachHang.Size = new Size(81, 19);
            labelKhachHang.TabIndex = 8;
            labelKhachHang.Text = "Khách hàng";
            txtTenSP.Location = new Point(128, 209);
            txtTenSP.Name = "txtTenSP";
            txtTenSP.ReadOnly = true;
            txtTenSP.Size = new Size(182, 25);
            txtTenSP.TabIndex = 7;
            labelTenSP.AutoSize = true;
            labelTenSP.Location = new Point(24, 212);
            labelTenSP.Name = "labelTenSP";
            labelTenSP.Size = new Size(91, 19);
            labelTenSP.TabIndex = 6;
            labelTenSP.Text = "Tên sản phẩm";
            txtMaSP.Location = new Point(128, 156);
            txtMaSP.Name = "txtMaSP";
            txtMaSP.ReadOnly = true;
            txtMaSP.Size = new Size(182, 25);
            txtMaSP.TabIndex = 5;
            labelMaSP.AutoSize = true;
            labelMaSP.Location = new Point(24, 159);
            labelMaSP.Name = "labelMaSP";
            labelMaSP.Size = new Size(46, 19);
            labelMaSP.TabIndex = 4;
            labelMaSP.Text = "Mã SP";
            txtMaHD.Location = new Point(128, 103);
            txtMaHD.Name = "txtMaHD";
            txtMaHD.ReadOnly = true;
            txtMaHD.Size = new Size(182, 25);
            txtMaHD.TabIndex = 3;
            labelMaHD.AutoSize = true;
            labelMaHD.Location = new Point(24, 106);
            labelMaHD.Name = "labelMaHD";
            labelMaHD.Size = new Size(48, 19);
            labelMaHD.TabIndex = 2;
            labelMaHD.Text = "Mã HĐ";
            txtMaCTHD.Location = new Point(128, 50);
            txtMaCTHD.Name = "txtMaCTHD";
            txtMaCTHD.ReadOnly = true;
            txtMaCTHD.Size = new Size(182, 25);
            txtMaCTHD.TabIndex = 1;
            labelMaCTHD.AutoSize = true;
            labelMaCTHD.Location = new Point(24, 53);
            labelMaCTHD.Name = "labelMaCTHD";
            labelMaCTHD.Size = new Size(67, 19);
            labelMaCTHD.TabIndex = 0;
            labelMaCTHD.Text = "Mã CTHĐ";
            grpDanhSach.Controls.Add(dgvChiTietHoaDon);
            grpDanhSach.Controls.Add(btnDong);
            grpDanhSach.Controls.Add(btnXoa);
            grpDanhSach.Controls.Add(btnLamMoi);
            grpDanhSach.Controls.Add(btnInHoaDon);
            grpDanhSach.Controls.Add(btnXemChiTiet);
            grpDanhSach.Controls.Add(btnQuayLai);
            grpDanhSach.Controls.Add(btnTimKiem);
            grpDanhSach.Controls.Add(txtTimKiem);
            grpDanhSach.Controls.Add(labelTimKiem);
            grpDanhSach.Controls.Add(lblThongBao);
            grpDanhSach.Location = new Point(376, 18);
            grpDanhSach.Name = "grpDanhSach";
            grpDanhSach.Size = new Size(834, 630);
            grpDanhSach.TabIndex = 1;
            grpDanhSach.TabStop = false;
            grpDanhSach.Text = "Danh sách chi tiết hóa đơn";
            dgvChiTietHoaDon.AllowUserToAddRows = false;
            dgvChiTietHoaDon.AllowUserToDeleteRows = false;
            dgvChiTietHoaDon.BackgroundColor = Color.White;
            dgvChiTietHoaDon.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            dgvChiTietHoaDon.Location = new Point(24, 84);
            dgvChiTietHoaDon.MultiSelect = false;
            dgvChiTietHoaDon.Name = "dgvChiTietHoaDon";
            dgvChiTietHoaDon.ReadOnly = true;
            dgvChiTietHoaDon.RowHeadersVisible = false;
            dgvChiTietHoaDon.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            dgvChiTietHoaDon.Size = new Size(786, 464);
            dgvChiTietHoaDon.TabIndex = 7;
            dgvChiTietHoaDon.SelectionChanged += dgvChiTietHoaDon_SelectionChanged;
            btnDong.BackColor = Color.FromArgb(71, 85, 105);
            btnDong.FlatAppearance.BorderSize = 0;
            btnDong.FlatStyle = FlatStyle.Flat;
            btnDong.ForeColor = Color.White;
            btnDong.Location = new Point(702, 586);
            btnDong.Name = "btnDong";
            btnDong.Size = new Size(108, 38);
            btnDong.TabIndex = 6;
            btnDong.Text = "Đóng";
            btnDong.UseVisualStyleBackColor = false;
            btnDong.Click += btnDong_Click;
            btnXoa.BackColor = Color.FromArgb(239, 68, 68);
            btnXoa.FlatAppearance.BorderSize = 0;
            btnXoa.FlatStyle = FlatStyle.Flat;
            btnXoa.ForeColor = Color.White;
            btnXoa.Location = new Point(580, 586);
            btnXoa.Name = "btnXoa";
            btnXoa.Size = new Size(108, 38);
            btnXoa.TabIndex = 5;
            btnXoa.Text = "Xóa chi tiết";
            btnXoa.UseVisualStyleBackColor = false;
            btnXoa.Click += btnXoa_Click;
            btnLamMoi.BackColor = Color.FromArgb(245, 158, 11);
            btnLamMoi.FlatAppearance.BorderSize = 0;
            btnLamMoi.FlatStyle = FlatStyle.Flat;
            btnLamMoi.ForeColor = Color.White;
            btnLamMoi.Location = new Point(458, 586);
            btnLamMoi.Name = "btnLamMoi";
            btnLamMoi.Size = new Size(108, 38);
            btnLamMoi.TabIndex = 4;
            btnLamMoi.Text = "Làm mới";
            btnLamMoi.UseVisualStyleBackColor = false;
            btnLamMoi.Click += btnLamMoi_Click;
            btnInHoaDon.BackColor = Color.FromArgb(37, 99, 235);
            btnInHoaDon.FlatAppearance.BorderSize = 0;
            btnInHoaDon.FlatStyle = FlatStyle.Flat;
            btnInHoaDon.ForeColor = Color.White;
            btnInHoaDon.Location = new Point(336, 586);
            btnInHoaDon.Name = "btnInHoaDon";
            btnInHoaDon.Size = new Size(108, 38);
            btnInHoaDon.TabIndex = 8;
            btnInHoaDon.Text = "In hóa đơn";
            btnInHoaDon.UseVisualStyleBackColor = false;
            btnInHoaDon.Click += btnInHoaDon_Click;
            btnXemChiTiet.BackColor = Color.FromArgb(13, 148, 136);
            btnXemChiTiet.FlatAppearance.BorderSize = 0;
            btnXemChiTiet.FlatStyle = FlatStyle.Flat;
            btnXemChiTiet.ForeColor = Color.White;
            btnXemChiTiet.Location = new Point(214, 586);
            btnXemChiTiet.Name = "btnXemChiTiet";
            btnXemChiTiet.Size = new Size(108, 38);
            btnXemChiTiet.TabIndex = 9;
            btnXemChiTiet.Text = "Xem chi tiết";
            btnXemChiTiet.UseVisualStyleBackColor = false;
            btnXemChiTiet.Click += btnXemChiTiet_Click;
            btnQuayLai.BackColor = Color.FromArgb(71, 85, 105);
            btnQuayLai.FlatAppearance.BorderSize = 0;
            btnQuayLai.FlatStyle = FlatStyle.Flat;
            btnQuayLai.ForeColor = Color.White;
            btnQuayLai.Location = new Point(92, 586);
            btnQuayLai.Name = "btnQuayLai";
            btnQuayLai.Size = new Size(108, 38);
            btnQuayLai.TabIndex = 10;
            btnQuayLai.Text = "Quay lại";
            btnQuayLai.UseVisualStyleBackColor = false;
            btnQuayLai.Visible = false;
            btnQuayLai.Click += btnQuayLai_Click;
            btnTimKiem.BackColor = Color.FromArgb(13, 148, 136);
            btnTimKiem.FlatAppearance.BorderSize = 0;
            btnTimKiem.FlatStyle = FlatStyle.Flat;
            btnTimKiem.ForeColor = Color.White;
            btnTimKiem.Location = new Point(722, 34);
            btnTimKiem.Name = "btnTimKiem";
            btnTimKiem.Size = new Size(88, 34);
            btnTimKiem.TabIndex = 3;
            btnTimKiem.Text = "Tìm kiếm";
            btnTimKiem.UseVisualStyleBackColor = false;
            btnTimKiem.Click += btnTimKiem_Click;
            txtTimKiem.Location = new Point(178, 39);
            txtTimKiem.Name = "txtTimKiem";
            txtTimKiem.PlaceholderText = "Nhập mã hóa đơn, tên sản phẩm hoặc khách hàng";
            txtTimKiem.Size = new Size(532, 25);
            txtTimKiem.TabIndex = 2;
            labelTimKiem.AutoSize = true;
            labelTimKiem.Location = new Point(24, 42);
            labelTimKiem.Name = "labelTimKiem";
            labelTimKiem.Size = new Size(139, 19);
            labelTimKiem.TabIndex = 1;
            labelTimKiem.Text = "Tìm chi tiết hóa đơn";
            lblThongBao.AutoSize = false;
            lblThongBao.ForeColor = Color.FromArgb(13, 148, 136);
            lblThongBao.Location = new Point(24, 555);
            lblThongBao.Name = "lblThongBao";
            lblThongBao.Size = new Size(786, 24);
            lblThongBao.TabIndex = 0;
            lblThongBao.Text = "Sẵn sàng quản lý dữ liệu.";
            AutoScaleDimensions = new SizeF(7F, 17F);
            AutoScaleMode = AutoScaleMode.Font;
            BackColor = Color.FromArgb(240, 253, 250);
            ClientSize = new Size(1228, 666);
            Controls.Add(grpDanhSach);
            Controls.Add(grpThongTin);
            Font = new Font("Segoe UI", 10F, FontStyle.Regular, GraphicsUnit.Point);
            FormBorderStyle = FormBorderStyle.FixedSingle;
            MaximizeBox = false;
            Name = "frmChiTietHoaDon";
            StartPosition = FormStartPosition.CenterParent;
            Text = "Quản lý chi tiết hóa đơn";
            Load += frmChiTietHoaDon_Load;
            grpThongTin.ResumeLayout(false);
            grpThongTin.PerformLayout();
            grpDanhSach.ResumeLayout(false);
            grpDanhSach.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)dgvChiTietHoaDon).EndInit();
            ResumeLayout(false);
        }

        #endregion

        private GroupBox grpThongTin;
        private TextBox txtThanhTien;
        private Label labelThanhTien;
        private TextBox txtDonGia;
        private Label labelDonGia;
        private TextBox txtSoLuong;
        private Label labelSoLuong;
        private TextBox txtNgayLap;
        private Label labelNgayLap;
        private TextBox txtNhanVien;
        private Label labelNhanVien;
        private TextBox txtKhachHang;
        private Label labelKhachHang;
        private TextBox txtTenSP;
        private Label labelTenSP;
        private TextBox txtMaSP;
        private Label labelMaSP;
        private TextBox txtMaHD;
        private Label labelMaHD;
        private TextBox txtMaCTHD;
        private Label labelMaCTHD;
        private GroupBox grpDanhSach;
        private DataGridView dgvChiTietHoaDon;
        private Button btnDong;
        private Button btnXoa;
        private Button btnLamMoi;
        private Button btnInHoaDon;
        private Button btnXemChiTiet;
        private Button btnQuayLai;
        private Button btnTimKiem;
        private TextBox txtTimKiem;
        private Label labelTimKiem;
        private Label lblThongBao;
    }
}
