namespace QuanLyBanHang.GUI
{
    partial class frmHoaDon
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }

            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        private void InitializeComponent()
        {
            grpLapHoaDon = new GroupBox();
            lblThongBao = new Label();
            btnDong = new Button();
            btnLuuHoaDon = new Button();
            btnXoaGioHang = new Button();
            btnBoSanPham = new Button();
            lblTongTien = new Label();
            labelTongTien = new Label();
            dgvChiTietTao = new DataGridView();
            grpThemSanPham = new GroupBox();
            btnThemSanPham = new Button();
            nudSoLuongBan = new NumericUpDown();
            labelSoLuongBan = new Label();
            lblTonKho = new Label();
            labelTonKho = new Label();
            lblDonGia = new Label();
            labelDonGia = new Label();
            cboSanPham = new ComboBox();
            labelSanPham = new Label();
            dtpNgayLap = new DateTimePicker();
            labelNgayLap = new Label();
            cboKhachHang = new ComboBox();
            labelKhachHang = new Label();
            cboNhanVien = new ComboBox();
            labelNhanVien = new Label();
            grpLichSuHoaDon = new GroupBox();
            lblThongTinHoaDon = new Label();
            dgvChiTietLichSu = new DataGridView();
            labelChiTietLichSu = new Label();
            dgvHoaDon = new DataGridView();
            btnXoaHoaDon = new Button();
            btnTimKiem = new Button();
            txtTimKiem = new TextBox();
            labelTimKiem = new Label();
            grpLapHoaDon.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)dgvChiTietTao).BeginInit();
            grpThemSanPham.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)nudSoLuongBan).BeginInit();
            grpLichSuHoaDon.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)dgvChiTietLichSu).BeginInit();
            ((System.ComponentModel.ISupportInitialize)dgvHoaDon).BeginInit();
            SuspendLayout();
            grpLapHoaDon.Controls.Add(lblThongBao);
            grpLapHoaDon.Controls.Add(btnDong);
            grpLapHoaDon.Controls.Add(btnLuuHoaDon);
            grpLapHoaDon.Controls.Add(btnXoaGioHang);
            grpLapHoaDon.Controls.Add(btnBoSanPham);
            grpLapHoaDon.Controls.Add(lblTongTien);
            grpLapHoaDon.Controls.Add(labelTongTien);
            grpLapHoaDon.Controls.Add(dgvChiTietTao);
            grpLapHoaDon.Controls.Add(grpThemSanPham);
            grpLapHoaDon.Controls.Add(dtpNgayLap);
            grpLapHoaDon.Controls.Add(labelNgayLap);
            grpLapHoaDon.Controls.Add(cboKhachHang);
            grpLapHoaDon.Controls.Add(labelKhachHang);
            grpLapHoaDon.Controls.Add(cboNhanVien);
            grpLapHoaDon.Controls.Add(labelNhanVien);
            grpLapHoaDon.Location = new Point(18, 18);
            grpLapHoaDon.Name = "grpLapHoaDon";
            grpLapHoaDon.Size = new Size(640, 744);
            grpLapHoaDon.TabIndex = 0;
            grpLapHoaDon.TabStop = false;
            grpLapHoaDon.Text = "Lập hóa đơn";
            lblThongBao.AutoSize = true;
            lblThongBao.ForeColor = Color.FromArgb(13, 148, 136);
            lblThongBao.Location = new Point(24, 705);
            lblThongBao.Name = "lblThongBao";
            lblThongBao.Size = new Size(150, 19);
            lblThongBao.TabIndex = 14;
            lblThongBao.Text = "Sẵn sàng lập hóa đơn.";
            btnDong.BackColor = Color.FromArgb(71, 85, 105);
            btnDong.FlatAppearance.BorderSize = 0;
            btnDong.FlatStyle = FlatStyle.Flat;
            btnDong.ForeColor = Color.White;
            btnDong.Location = new Point(512, 651);
            btnDong.Name = "btnDong";
            btnDong.Size = new Size(102, 38);
            btnDong.TabIndex = 13;
            btnDong.Text = "Đóng";
            btnDong.UseVisualStyleBackColor = false;
            btnDong.Click += btnDong_Click;
            btnLuuHoaDon.BackColor = Color.FromArgb(13, 148, 136);
            btnLuuHoaDon.FlatAppearance.BorderSize = 0;
            btnLuuHoaDon.FlatStyle = FlatStyle.Flat;
            btnLuuHoaDon.ForeColor = Color.White;
            btnLuuHoaDon.Location = new Point(390, 651);
            btnLuuHoaDon.Name = "btnLuuHoaDon";
            btnLuuHoaDon.Size = new Size(112, 38);
            btnLuuHoaDon.TabIndex = 12;
            btnLuuHoaDon.Text = "Lưu hóa đơn";
            btnLuuHoaDon.UseVisualStyleBackColor = false;
            btnLuuHoaDon.Click += btnLuuHoaDon_Click;
            btnXoaGioHang.BackColor = Color.FromArgb(245, 158, 11);
            btnXoaGioHang.FlatAppearance.BorderSize = 0;
            btnXoaGioHang.FlatStyle = FlatStyle.Flat;
            btnXoaGioHang.ForeColor = Color.White;
            btnXoaGioHang.Location = new Point(268, 651);
            btnXoaGioHang.Name = "btnXoaGioHang";
            btnXoaGioHang.Size = new Size(112, 38);
            btnXoaGioHang.TabIndex = 11;
            btnXoaGioHang.Text = "Làm mới phiếu";
            btnXoaGioHang.UseVisualStyleBackColor = false;
            btnXoaGioHang.Click += btnXoaGioHang_Click;
            btnBoSanPham.BackColor = Color.FromArgb(239, 68, 68);
            btnBoSanPham.FlatAppearance.BorderSize = 0;
            btnBoSanPham.FlatStyle = FlatStyle.Flat;
            btnBoSanPham.ForeColor = Color.White;
            btnBoSanPham.Location = new Point(144, 651);
            btnBoSanPham.Name = "btnBoSanPham";
            btnBoSanPham.Size = new Size(112, 38);
            btnBoSanPham.TabIndex = 10;
            btnBoSanPham.Text = "Bỏ sản phẩm";
            btnBoSanPham.UseVisualStyleBackColor = false;
            btnBoSanPham.Click += btnBoSanPham_Click;
            lblTongTien.Font = new Font("Segoe UI Semibold", 18F, FontStyle.Bold, GraphicsUnit.Point);
            lblTongTien.ForeColor = Color.FromArgb(15, 118, 110);
            lblTongTien.Location = new Point(389, 597);
            lblTongTien.Name = "lblTongTien";
            lblTongTien.Size = new Size(225, 32);
            lblTongTien.TabIndex = 9;
            lblTongTien.Text = "0 VNĐ";
            lblTongTien.TextAlign = ContentAlignment.MiddleRight;
            labelTongTien.AutoSize = true;
            labelTongTien.Font = new Font("Segoe UI Semibold", 12F, FontStyle.Bold, GraphicsUnit.Point);
            labelTongTien.Location = new Point(24, 604);
            labelTongTien.Name = "labelTongTien";
            labelTongTien.Size = new Size(82, 21);
            labelTongTien.TabIndex = 8;
            labelTongTien.Text = "Tổng tiền";
            dgvChiTietTao.AllowUserToAddRows = false;
            dgvChiTietTao.AllowUserToDeleteRows = false;
            dgvChiTietTao.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.None;
            dgvChiTietTao.BackgroundColor = Color.White;
            dgvChiTietTao.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            dgvChiTietTao.Location = new Point(24, 338);
            dgvChiTietTao.MultiSelect = false;
            dgvChiTietTao.Name = "dgvChiTietTao";
            dgvChiTietTao.ReadOnly = true;
            dgvChiTietTao.RowHeadersVisible = false;
            dgvChiTietTao.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            dgvChiTietTao.Size = new Size(590, 246);
            dgvChiTietTao.TabIndex = 7;
            grpThemSanPham.Controls.Add(btnThemSanPham);
            grpThemSanPham.Controls.Add(nudSoLuongBan);
            grpThemSanPham.Controls.Add(labelSoLuongBan);
            grpThemSanPham.Controls.Add(lblTonKho);
            grpThemSanPham.Controls.Add(labelTonKho);
            grpThemSanPham.Controls.Add(lblDonGia);
            grpThemSanPham.Controls.Add(labelDonGia);
            grpThemSanPham.Controls.Add(cboSanPham);
            grpThemSanPham.Controls.Add(labelSanPham);
            grpThemSanPham.Location = new Point(24, 126);
            grpThemSanPham.Name = "grpThemSanPham";
            grpThemSanPham.Size = new Size(590, 192);
            grpThemSanPham.TabIndex = 6;
            grpThemSanPham.TabStop = false;
            grpThemSanPham.Text = "Thêm sản phẩm";
            btnThemSanPham.BackColor = Color.FromArgb(13, 148, 136);
            btnThemSanPham.FlatAppearance.BorderSize = 0;
            btnThemSanPham.FlatStyle = FlatStyle.Flat;
            btnThemSanPham.ForeColor = Color.White;
            btnThemSanPham.Location = new Point(431, 130);
            btnThemSanPham.Name = "btnThemSanPham";
            btnThemSanPham.Size = new Size(135, 38);
            btnThemSanPham.TabIndex = 8;
            btnThemSanPham.Text = "Thêm vào hóa đơn";
            btnThemSanPham.UseVisualStyleBackColor = false;
            btnThemSanPham.Click += btnThemSanPham_Click;
            nudSoLuongBan.Location = new Point(130, 136);
            nudSoLuongBan.Maximum = new decimal(new int[] { 1000, 0, 0, 0 });
            nudSoLuongBan.Minimum = new decimal(new int[] { 1, 0, 0, 0 });
            nudSoLuongBan.Name = "nudSoLuongBan";
            nudSoLuongBan.Size = new Size(100, 25);
            nudSoLuongBan.TabIndex = 7;
            nudSoLuongBan.Value = new decimal(new int[] { 1, 0, 0, 0 });
            labelSoLuongBan.AutoSize = true;
            labelSoLuongBan.Location = new Point(24, 139);
            labelSoLuongBan.Name = "labelSoLuongBan";
            labelSoLuongBan.Size = new Size(68, 19);
            labelSoLuongBan.TabIndex = 6;
            labelSoLuongBan.Text = "Số lượng";
            lblTonKho.AutoSize = true;
            lblTonKho.Font = new Font("Segoe UI Semibold", 11F, FontStyle.Bold, GraphicsUnit.Point);
            lblTonKho.ForeColor = Color.FromArgb(15, 118, 110);
            lblTonKho.Location = new Point(448, 82);
            lblTonKho.Name = "lblTonKho";
            lblTonKho.Size = new Size(17, 20);
            lblTonKho.TabIndex = 5;
            lblTonKho.Text = "0";
            labelTonKho.AutoSize = true;
            labelTonKho.Location = new Point(364, 82);
            labelTonKho.Name = "labelTonKho";
            labelTonKho.Size = new Size(62, 19);
            labelTonKho.TabIndex = 4;
            labelTonKho.Text = "Tồn kho";
            lblDonGia.AutoSize = true;
            lblDonGia.Font = new Font("Segoe UI Semibold", 11F, FontStyle.Bold, GraphicsUnit.Point);
            lblDonGia.ForeColor = Color.FromArgb(15, 118, 110);
            lblDonGia.Location = new Point(130, 82);
            lblDonGia.Name = "lblDonGia";
            lblDonGia.Size = new Size(56, 20);
            lblDonGia.TabIndex = 3;
            lblDonGia.Text = "0 VNĐ";
            labelDonGia.AutoSize = true;
            labelDonGia.Location = new Point(24, 82);
            labelDonGia.Name = "labelDonGia";
            labelDonGia.Size = new Size(58, 19);
            labelDonGia.TabIndex = 2;
            labelDonGia.Text = "Đơn giá";
            cboSanPham.DropDownStyle = ComboBoxStyle.DropDownList;
            cboSanPham.FormattingEnabled = true;
            cboSanPham.Location = new Point(130, 36);
            cboSanPham.Name = "cboSanPham";
            cboSanPham.Size = new Size(436, 25);
            cboSanPham.TabIndex = 1;
            cboSanPham.SelectedIndexChanged += cboSanPham_SelectedIndexChanged;
            labelSanPham.AutoSize = true;
            labelSanPham.Location = new Point(24, 39);
            labelSanPham.Name = "labelSanPham";
            labelSanPham.Size = new Size(71, 19);
            labelSanPham.TabIndex = 0;
            labelSanPham.Text = "Sản phẩm";
            dtpNgayLap.CustomFormat = "dd/MM/yyyy HH:mm";
            dtpNgayLap.Format = DateTimePickerFormat.Custom;
            dtpNgayLap.Location = new Point(458, 74);
            dtpNgayLap.Name = "dtpNgayLap";
            dtpNgayLap.Size = new Size(156, 25);
            dtpNgayLap.TabIndex = 5;
            labelNgayLap.AutoSize = true;
            labelNgayLap.Location = new Point(376, 77);
            labelNgayLap.Name = "labelNgayLap";
            labelNgayLap.Size = new Size(64, 19);
            labelNgayLap.TabIndex = 4;
            labelNgayLap.Text = "Ngày lập";
            cboKhachHang.DropDownStyle = ComboBoxStyle.DropDownList;
            cboKhachHang.FormattingEnabled = true;
            cboKhachHang.Location = new Point(130, 74);
            cboKhachHang.Name = "cboKhachHang";
            cboKhachHang.Size = new Size(214, 25);
            cboKhachHang.TabIndex = 3;
            labelKhachHang.AutoSize = true;
            labelKhachHang.Location = new Point(24, 77);
            labelKhachHang.Name = "labelKhachHang";
            labelKhachHang.Size = new Size(81, 19);
            labelKhachHang.TabIndex = 2;
            labelKhachHang.Text = "Khách hàng";
            cboNhanVien.DropDownStyle = ComboBoxStyle.DropDownList;
            cboNhanVien.FormattingEnabled = true;
            cboNhanVien.Location = new Point(130, 34);
            cboNhanVien.Name = "cboNhanVien";
            cboNhanVien.Size = new Size(484, 25);
            cboNhanVien.TabIndex = 1;
            labelNhanVien.AutoSize = true;
            labelNhanVien.Location = new Point(24, 37);
            labelNhanVien.Name = "labelNhanVien";
            labelNhanVien.Size = new Size(73, 19);
            labelNhanVien.TabIndex = 0;
            labelNhanVien.Text = "Nhân viên";
            grpLichSuHoaDon.Controls.Add(lblThongTinHoaDon);
            grpLichSuHoaDon.Controls.Add(dgvChiTietLichSu);
            grpLichSuHoaDon.Controls.Add(labelChiTietLichSu);
            grpLichSuHoaDon.Controls.Add(dgvHoaDon);
            grpLichSuHoaDon.Controls.Add(btnXoaHoaDon);
            grpLichSuHoaDon.Controls.Add(btnTimKiem);
            grpLichSuHoaDon.Controls.Add(txtTimKiem);
            grpLichSuHoaDon.Controls.Add(labelTimKiem);
            grpLichSuHoaDon.Location = new Point(676, 18);
            grpLichSuHoaDon.Name = "grpLichSuHoaDon";
            grpLichSuHoaDon.Size = new Size(694, 744);
            grpLichSuHoaDon.TabIndex = 1;
            grpLichSuHoaDon.TabStop = false;
            grpLichSuHoaDon.Text = "Quản lý hóa đơn";
            lblThongTinHoaDon.AutoSize = true;
            lblThongTinHoaDon.Font = new Font("Segoe UI Semibold", 10.5F, FontStyle.Bold, GraphicsUnit.Point);
            lblThongTinHoaDon.ForeColor = Color.FromArgb(15, 118, 110);
            lblThongTinHoaDon.Location = new Point(24, 404);
            lblThongTinHoaDon.MaximumSize = new Size(640, 0);
            lblThongTinHoaDon.Name = "lblThongTinHoaDon";
            lblThongTinHoaDon.Size = new Size(116, 19);
            lblThongTinHoaDon.TabIndex = 7;
            lblThongTinHoaDon.Text = "Chưa chọn hóa đơn.";
            dgvChiTietLichSu.AllowUserToAddRows = false;
            dgvChiTietLichSu.AllowUserToDeleteRows = false;
            dgvChiTietLichSu.BackgroundColor = Color.White;
            dgvChiTietLichSu.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            dgvChiTietLichSu.Location = new Point(24, 444);
            dgvChiTietLichSu.MultiSelect = false;
            dgvChiTietLichSu.Name = "dgvChiTietLichSu";
            dgvChiTietLichSu.ReadOnly = true;
            dgvChiTietLichSu.RowHeadersVisible = false;
            dgvChiTietLichSu.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            dgvChiTietLichSu.Size = new Size(646, 274);
            dgvChiTietLichSu.TabIndex = 6;
            labelChiTietLichSu.AutoSize = true;
            labelChiTietLichSu.Font = new Font("Segoe UI Semibold", 11F, FontStyle.Bold, GraphicsUnit.Point);
            labelChiTietLichSu.Location = new Point(24, 374);
            labelChiTietLichSu.Name = "labelChiTietLichSu";
            labelChiTietLichSu.Size = new Size(121, 20);
            labelChiTietLichSu.TabIndex = 5;
            labelChiTietLichSu.Text = "Chi tiết hóa đơn";
            dgvHoaDon.AllowUserToAddRows = false;
            dgvHoaDon.AllowUserToDeleteRows = false;
            dgvHoaDon.BackgroundColor = Color.White;
            dgvHoaDon.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            dgvHoaDon.Location = new Point(24, 86);
            dgvHoaDon.MultiSelect = false;
            dgvHoaDon.Name = "dgvHoaDon";
            dgvHoaDon.ReadOnly = true;
            dgvHoaDon.RowHeadersVisible = false;
            dgvHoaDon.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            dgvHoaDon.Size = new Size(646, 266);
            dgvHoaDon.TabIndex = 4;
            dgvHoaDon.SelectionChanged += dgvHoaDon_SelectionChanged;
            btnXoaHoaDon.BackColor = Color.FromArgb(239, 68, 68);
            btnXoaHoaDon.FlatAppearance.BorderSize = 0;
            btnXoaHoaDon.FlatStyle = FlatStyle.Flat;
            btnXoaHoaDon.ForeColor = Color.White;
            btnXoaHoaDon.Location = new Point(570, 34);
            btnXoaHoaDon.Name = "btnXoaHoaDon";
            btnXoaHoaDon.Size = new Size(100, 34);
            btnXoaHoaDon.TabIndex = 3;
            btnXoaHoaDon.Text = "Xóa hóa đơn";
            btnXoaHoaDon.UseVisualStyleBackColor = false;
            btnXoaHoaDon.Click += btnXoaHoaDon_Click;
            btnTimKiem.BackColor = Color.FromArgb(13, 148, 136);
            btnTimKiem.FlatAppearance.BorderSize = 0;
            btnTimKiem.FlatStyle = FlatStyle.Flat;
            btnTimKiem.ForeColor = Color.White;
            btnTimKiem.Location = new Point(471, 34);
            btnTimKiem.Name = "btnTimKiem";
            btnTimKiem.Size = new Size(88, 34);
            btnTimKiem.TabIndex = 2;
            btnTimKiem.Text = "Tìm kiếm";
            btnTimKiem.UseVisualStyleBackColor = false;
            btnTimKiem.Click += btnTimKiem_Click;
            txtTimKiem.Location = new Point(121, 39);
            txtTimKiem.Name = "txtTimKiem";
            txtTimKiem.PlaceholderText = "Nhập mã hóa đơn hoặc tên khách hàng";
            txtTimKiem.Size = new Size(338, 25);
            txtTimKiem.TabIndex = 1;
            labelTimKiem.AutoSize = true;
            labelTimKiem.Location = new Point(24, 42);
            labelTimKiem.Name = "labelTimKiem";
            labelTimKiem.Size = new Size(63, 19);
            labelTimKiem.TabIndex = 0;
            labelTimKiem.Text = "Tìm kiếm";
            AutoScaleDimensions = new SizeF(7F, 17F);
            AutoScaleMode = AutoScaleMode.Font;
            BackColor = Color.FromArgb(240, 253, 250);
            ClientSize = new Size(1388, 780);
            Controls.Add(grpLichSuHoaDon);
            Controls.Add(grpLapHoaDon);
            Font = new Font("Segoe UI", 10F, FontStyle.Regular, GraphicsUnit.Point);
            FormBorderStyle = FormBorderStyle.FixedSingle;
            MaximizeBox = false;
            Name = "frmHoaDon";
            StartPosition = FormStartPosition.CenterParent;
            Text = "Quản lý hóa đơn";
            Load += frmHoaDon_Load;
            grpLapHoaDon.ResumeLayout(false);
            grpLapHoaDon.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)dgvChiTietTao).EndInit();
            grpThemSanPham.ResumeLayout(false);
            grpThemSanPham.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)nudSoLuongBan).EndInit();
            grpLichSuHoaDon.ResumeLayout(false);
            grpLichSuHoaDon.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)dgvChiTietLichSu).EndInit();
            ((System.ComponentModel.ISupportInitialize)dgvHoaDon).EndInit();
            ResumeLayout(false);
        }

        #endregion

        private GroupBox grpLapHoaDon;
        private Label lblThongBao;
        private Button btnDong;
        private Button btnLuuHoaDon;
        private Button btnXoaGioHang;
        private Button btnBoSanPham;
        private Label lblTongTien;
        private Label labelTongTien;
        private DataGridView dgvChiTietTao;
        private GroupBox grpThemSanPham;
        private Button btnThemSanPham;
        private NumericUpDown nudSoLuongBan;
        private Label labelSoLuongBan;
        private Label lblTonKho;
        private Label labelTonKho;
        private Label lblDonGia;
        private Label labelDonGia;
        private ComboBox cboSanPham;
        private Label labelSanPham;
        private DateTimePicker dtpNgayLap;
        private Label labelNgayLap;
        private ComboBox cboKhachHang;
        private Label labelKhachHang;
        private ComboBox cboNhanVien;
        private Label labelNhanVien;
        private GroupBox grpLichSuHoaDon;
        private Label lblThongTinHoaDon;
        private DataGridView dgvChiTietLichSu;
        private Label labelChiTietLichSu;
        private DataGridView dgvHoaDon;
        private Button btnXoaHoaDon;
        private Button btnTimKiem;
        private TextBox txtTimKiem;
        private Label labelTimKiem;
    }
}
