namespace QuanLyBanHang.GUI
{
    partial class frmTrangChu
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }

            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        private void InitializeComponent()
        {
            panelSidebar = new Panel();
            labelSidebarNote = new Label();
            labelSidebarTitle = new Label();
            btnThongKe = new Button();
            btnChiTietHoaDon = new Button();
            btnHoaDon = new Button();
            btnKhachHang = new Button();
            btnNhanVien = new Button();
            btnNhaCungCap = new Button();
            btnLoaiSanPham = new Button();
            btnSanPham = new Button();
            panelHeader = new Panel();
            btnDangXuat = new Button();
            lblQuyen = new Label();
            labelQuyen = new Label();
            lblHoTen = new Label();
            labelNguoiDung = new Label();
            panelContent = new Panel();
            panelWorkflow = new Panel();
            labelWorkflowText = new Label();
            labelWorkflowTitle = new Label();
            panelWelcome = new Panel();
            labelWelcomeNote = new Label();
            lblLoiChao = new Label();
            panelSidebar.SuspendLayout();
            panelHeader.SuspendLayout();
            panelContent.SuspendLayout();
            panelWorkflow.SuspendLayout();
            panelWelcome.SuspendLayout();
            SuspendLayout();
            panelSidebar.BackColor = Color.FromArgb(15, 118, 110);
            panelSidebar.Controls.Add(labelSidebarNote);
            panelSidebar.Controls.Add(labelSidebarTitle);
            panelSidebar.Controls.Add(btnThongKe);
            panelSidebar.Controls.Add(btnChiTietHoaDon);
            panelSidebar.Controls.Add(btnHoaDon);
            panelSidebar.Controls.Add(btnKhachHang);
            panelSidebar.Controls.Add(btnNhanVien);
            panelSidebar.Controls.Add(btnNhaCungCap);
            panelSidebar.Controls.Add(btnLoaiSanPham);
            panelSidebar.Controls.Add(btnSanPham);
            panelSidebar.Dock = DockStyle.Left;
            panelSidebar.Location = new Point(0, 0);
            panelSidebar.Name = "panelSidebar";
            panelSidebar.Size = new Size(280, 720);
            labelSidebarNote.AutoSize = true;
            labelSidebarNote.Font = new Font("Segoe UI", 10.5F, FontStyle.Regular, GraphicsUnit.Point);
            labelSidebarNote.ForeColor = Color.FromArgb(204, 251, 241);
            labelSidebarNote.Location = new Point(23, 74);
            labelSidebarNote.MaximumSize = new Size(230, 0);
            labelSidebarNote.Name = "labelSidebarNote";
            labelSidebarNote.Size = new Size(215, 38);
            labelSidebarNote.Text = "Điều hướng nhanh đến các phân hệ quản lý.";
            labelSidebarTitle.AutoSize = true;
            labelSidebarTitle.Font = new Font("Segoe UI Semibold", 20F, FontStyle.Bold, GraphicsUnit.Point);
            labelSidebarTitle.ForeColor = Color.White;
            labelSidebarTitle.Location = new Point(18, 25);
            labelSidebarTitle.Name = "labelSidebarTitle";
            labelSidebarTitle.Size = new Size(188, 37);
            labelSidebarTitle.Text = "Trà sữa UTEHY";
            btnThongKe.BackColor = Color.FromArgb(19, 78, 74);
            btnThongKe.FlatAppearance.BorderSize = 0;
            btnThongKe.FlatStyle = FlatStyle.Flat;
            btnThongKe.Font = new Font("Segoe UI Semibold", 10.5F, FontStyle.Bold, GraphicsUnit.Point);
            btnThongKe.ForeColor = Color.White;
            btnThongKe.Location = new Point(20, 508);
            btnThongKe.Name = "btnThongKe";
            btnThongKe.Size = new Size(240, 46);
            btnThongKe.TabStop = false;
            btnThongKe.Text = "Thống kê doanh thu";
            btnThongKe.UseVisualStyleBackColor = false;
            btnThongKe.Click += btnThongKe_Click;
            btnChiTietHoaDon.BackColor = Color.FromArgb(19, 78, 74);
            btnChiTietHoaDon.FlatAppearance.BorderSize = 0;
            btnChiTietHoaDon.FlatStyle = FlatStyle.Flat;
            btnChiTietHoaDon.Font = new Font("Segoe UI Semibold", 10.5F, FontStyle.Bold, GraphicsUnit.Point);
            btnChiTietHoaDon.ForeColor = Color.White;
            btnChiTietHoaDon.Location = new Point(20, 454);
            btnChiTietHoaDon.Name = "btnChiTietHoaDon";
            btnChiTietHoaDon.Size = new Size(240, 46);
            btnChiTietHoaDon.TabStop = false;
            btnChiTietHoaDon.Text = "Chi tiết hóa đơn";
            btnChiTietHoaDon.UseVisualStyleBackColor = false;
            btnChiTietHoaDon.Click += btnChiTietHoaDon_Click;
            btnHoaDon.BackColor = Color.FromArgb(19, 78, 74);
            btnHoaDon.FlatAppearance.BorderSize = 0;
            btnHoaDon.FlatStyle = FlatStyle.Flat;
            btnHoaDon.Font = new Font("Segoe UI Semibold", 10.5F, FontStyle.Bold, GraphicsUnit.Point);
            btnHoaDon.ForeColor = Color.White;
            btnHoaDon.Location = new Point(20, 400);
            btnHoaDon.Name = "btnHoaDon";
            btnHoaDon.Size = new Size(240, 46);
            btnHoaDon.TabStop = false;
            btnHoaDon.Text = "Hóa đơn";
            btnHoaDon.UseVisualStyleBackColor = false;
            btnHoaDon.Click += btnHoaDon_Click;
            btnKhachHang.BackColor = Color.FromArgb(19, 78, 74);
            btnKhachHang.FlatAppearance.BorderSize = 0;
            btnKhachHang.FlatStyle = FlatStyle.Flat;
            btnKhachHang.Font = new Font("Segoe UI Semibold", 10.5F, FontStyle.Bold, GraphicsUnit.Point);
            btnKhachHang.ForeColor = Color.White;
            btnKhachHang.Location = new Point(20, 346);
            btnKhachHang.Name = "btnKhachHang";
            btnKhachHang.Size = new Size(240, 46);
            btnKhachHang.TabStop = false;
            btnKhachHang.Text = "Khách hàng";
            btnKhachHang.UseVisualStyleBackColor = false;
            btnKhachHang.Click += btnKhachHang_Click;
            btnNhanVien.BackColor = Color.FromArgb(19, 78, 74);
            btnNhanVien.FlatAppearance.BorderSize = 0;
            btnNhanVien.FlatStyle = FlatStyle.Flat;
            btnNhanVien.Font = new Font("Segoe UI Semibold", 10.5F, FontStyle.Bold, GraphicsUnit.Point);
            btnNhanVien.ForeColor = Color.White;
            btnNhanVien.Location = new Point(20, 292);
            btnNhanVien.Name = "btnNhanVien";
            btnNhanVien.Size = new Size(240, 46);
            btnNhanVien.TabStop = false;
            btnNhanVien.Text = "Nhân viên";
            btnNhanVien.UseVisualStyleBackColor = false;
            btnNhanVien.Click += btnNhanVien_Click;
            btnNhaCungCap.BackColor = Color.FromArgb(19, 78, 74);
            btnNhaCungCap.FlatAppearance.BorderSize = 0;
            btnNhaCungCap.FlatStyle = FlatStyle.Flat;
            btnNhaCungCap.Font = new Font("Segoe UI Semibold", 10.5F, FontStyle.Bold, GraphicsUnit.Point);
            btnNhaCungCap.ForeColor = Color.White;
            btnNhaCungCap.Location = new Point(20, 238);
            btnNhaCungCap.Name = "btnNhaCungCap";
            btnNhaCungCap.Size = new Size(240, 46);
            btnNhaCungCap.TabStop = false;
            btnNhaCungCap.Text = "Nhà cung cấp";
            btnNhaCungCap.UseVisualStyleBackColor = false;
            btnNhaCungCap.Click += btnNhaCungCap_Click;
            btnLoaiSanPham.BackColor = Color.FromArgb(19, 78, 74);
            btnLoaiSanPham.FlatAppearance.BorderSize = 0;
            btnLoaiSanPham.FlatStyle = FlatStyle.Flat;
            btnLoaiSanPham.Font = new Font("Segoe UI Semibold", 10.5F, FontStyle.Bold, GraphicsUnit.Point);
            btnLoaiSanPham.ForeColor = Color.White;
            btnLoaiSanPham.Location = new Point(20, 184);
            btnLoaiSanPham.Name = "btnLoaiSanPham";
            btnLoaiSanPham.Size = new Size(240, 46);
            btnLoaiSanPham.TabStop = false;
            btnLoaiSanPham.Text = "Loại sản phẩm";
            btnLoaiSanPham.UseVisualStyleBackColor = false;
            btnLoaiSanPham.Click += btnLoaiSanPham_Click;
            btnSanPham.BackColor = Color.FromArgb(19, 78, 74);
            btnSanPham.FlatAppearance.BorderSize = 0;
            btnSanPham.FlatStyle = FlatStyle.Flat;
            btnSanPham.Font = new Font("Segoe UI Semibold", 10.5F, FontStyle.Bold, GraphicsUnit.Point);
            btnSanPham.ForeColor = Color.White;
            btnSanPham.Location = new Point(20, 130);
            btnSanPham.Name = "btnSanPham";
            btnSanPham.Size = new Size(240, 46);
            btnSanPham.TabStop = false;
            btnSanPham.Text = "Sản phẩm";
            btnSanPham.UseVisualStyleBackColor = false;
            btnSanPham.Click += btnSanPham_Click;
            panelHeader.BackColor = Color.White;
            panelHeader.Controls.Add(btnDangXuat);
            panelHeader.Controls.Add(lblQuyen);
            panelHeader.Controls.Add(labelQuyen);
            panelHeader.Controls.Add(lblHoTen);
            panelHeader.Controls.Add(labelNguoiDung);
            panelHeader.Dock = DockStyle.Top;
            panelHeader.Location = new Point(280, 0);
            panelHeader.Name = "panelHeader";
            panelHeader.Size = new Size(900, 90);
            btnDangXuat.BackColor = Color.FromArgb(239, 68, 68);
            btnDangXuat.FlatAppearance.BorderSize = 0;
            btnDangXuat.FlatStyle = FlatStyle.Flat;
            btnDangXuat.Font = new Font("Segoe UI Semibold", 10.5F, FontStyle.Bold, GraphicsUnit.Point);
            btnDangXuat.ForeColor = Color.White;
            btnDangXuat.Location = new Point(742, 24);
            btnDangXuat.Name = "btnDangXuat";
            btnDangXuat.Size = new Size(126, 40);
            btnDangXuat.Text = "Đăng xuất";
            btnDangXuat.UseVisualStyleBackColor = false;
            btnDangXuat.Click += btnDangXuat_Click;
            lblQuyen.AutoSize = true;
            lblQuyen.Font = new Font("Segoe UI Semibold", 12.5F, FontStyle.Bold, GraphicsUnit.Point);
            lblQuyen.ForeColor = Color.FromArgb(13, 148, 136);
            lblQuyen.Location = new Point(330, 44);
            lblQuyen.Name = "lblQuyen";
            lblQuyen.Size = new Size(87, 23);
            lblQuyen.Text = "Nhân viên";
            labelQuyen.AutoSize = true;
            labelQuyen.Font = new Font("Segoe UI", 10.5F, FontStyle.Regular, GraphicsUnit.Point);
            labelQuyen.ForeColor = Color.FromArgb(75, 85, 99);
            labelQuyen.Location = new Point(330, 22);
            labelQuyen.Name = "labelQuyen";
            labelQuyen.Size = new Size(51, 19);
            labelQuyen.Text = "Quyền";
            lblHoTen.AutoSize = true;
            lblHoTen.Font = new Font("Segoe UI Semibold", 14F, FontStyle.Bold, GraphicsUnit.Point);
            lblHoTen.ForeColor = Color.FromArgb(17, 24, 39);
            lblHoTen.Location = new Point(31, 42);
            lblHoTen.Name = "lblHoTen";
            lblHoTen.Size = new Size(105, 25);
            lblHoTen.Text = "Người dùng";
            labelNguoiDung.AutoSize = true;
            labelNguoiDung.Font = new Font("Segoe UI", 10.5F, FontStyle.Regular, GraphicsUnit.Point);
            labelNguoiDung.ForeColor = Color.FromArgb(75, 85, 99);
            labelNguoiDung.Location = new Point(31, 20);
            labelNguoiDung.Name = "labelNguoiDung";
            labelNguoiDung.Size = new Size(83, 19);
            labelNguoiDung.Text = "Người dùng";
            panelContent.BackColor = Color.FromArgb(240, 253, 250);
            panelContent.Controls.Add(panelWorkflow);
            panelContent.Controls.Add(panelWelcome);
            panelContent.Dock = DockStyle.Fill;
            panelContent.Location = new Point(280, 90);
            panelContent.Name = "panelContent";
            panelContent.Padding = new Padding(28);
            panelContent.Size = new Size(900, 630);
            panelWorkflow.BackColor = Color.White;
            panelWorkflow.Controls.Add(labelWorkflowText);
            panelWorkflow.Controls.Add(labelWorkflowTitle);
            panelWorkflow.Location = new Point(28, 224);
            panelWorkflow.Name = "panelWorkflow";
            panelWorkflow.Size = new Size(844, 170);
            labelWorkflowText.AutoSize = true;
            labelWorkflowText.Font = new Font("Segoe UI", 11F, FontStyle.Regular, GraphicsUnit.Point);
            labelWorkflowText.ForeColor = Color.FromArgb(55, 65, 81);
            labelWorkflowText.Location = new Point(35, 74);
            labelWorkflowText.MaximumSize = new Size(760, 0);
            labelWorkflowText.Name = "labelWorkflowText";
            labelWorkflowText.Size = new Size(760, 40);
            labelWorkflowText.Text = "Đăng nhập -> Trang chủ -> Hóa đơn -> Chọn khách hàng -> Chọn sản phẩm -> Nhập số lượng -> Tính tổng tiền -> Lưu hóa đơn.";
            labelWorkflowTitle.AutoSize = true;
            labelWorkflowTitle.Font = new Font("Segoe UI Semibold", 16F, FontStyle.Bold, GraphicsUnit.Point);
            labelWorkflowTitle.ForeColor = Color.FromArgb(17, 24, 39);
            labelWorkflowTitle.Location = new Point(34, 28);
            labelWorkflowTitle.Name = "labelWorkflowTitle";
            labelWorkflowTitle.Size = new Size(191, 30);
            labelWorkflowTitle.Text = "Luồng xử lý bán hàng";
            panelWelcome.BackColor = Color.White;
            panelWelcome.Controls.Add(labelWelcomeNote);
            panelWelcome.Controls.Add(lblLoiChao);
            panelWelcome.Location = new Point(28, 28);
            panelWelcome.Name = "panelWelcome";
            panelWelcome.Size = new Size(844, 170);
            labelWelcomeNote.AutoSize = true;
            labelWelcomeNote.Font = new Font("Segoe UI", 12F, FontStyle.Regular, GraphicsUnit.Point);
            labelWelcomeNote.ForeColor = Color.FromArgb(71, 85, 105);
            labelWelcomeNote.Location = new Point(35, 89);
            labelWelcomeNote.MaximumSize = new Size(760, 0);
            labelWelcomeNote.Name = "labelWelcomeNote";
            labelWelcomeNote.Size = new Size(744, 21);
            labelWelcomeNote.Text = "Từ đây bạn có thể điều hướng đến sản phẩm, khách hàng, hóa đơn, nhà cung cấp và báo cáo doanh thu.";
            lblLoiChao.AutoSize = true;
            lblLoiChao.Font = new Font("Segoe UI Semibold", 24F, FontStyle.Bold, GraphicsUnit.Point);
            lblLoiChao.ForeColor = Color.FromArgb(15, 23, 42);
            lblLoiChao.Location = new Point(33, 33);
            lblLoiChao.Name = "lblLoiChao";
            lblLoiChao.Size = new Size(273, 45);
            lblLoiChao.Text = "Xin chào, Người dùng";
            AutoScaleDimensions = new SizeF(7F, 17F);
            AutoScaleMode = AutoScaleMode.Font;
            ClientSize = new Size(1180, 720);
            Controls.Add(panelContent);
            Controls.Add(panelHeader);
            Controls.Add(panelSidebar);
            Font = new Font("Segoe UI", 10F, FontStyle.Regular, GraphicsUnit.Point);
            FormBorderStyle = FormBorderStyle.FixedSingle;
            MaximizeBox = false;
            Name = "frmTrangChu";
            StartPosition = FormStartPosition.CenterScreen;
            Text = "Quản lý bán hàng trà sữa";
            panelSidebar.ResumeLayout(false);
            panelSidebar.PerformLayout();
            panelHeader.ResumeLayout(false);
            panelHeader.PerformLayout();
            panelContent.ResumeLayout(false);
            panelWorkflow.ResumeLayout(false);
            panelWorkflow.PerformLayout();
            panelWelcome.ResumeLayout(false);
            panelWelcome.PerformLayout();
            ResumeLayout(false);
        }

        #endregion

        private Panel panelSidebar;
        private Label labelSidebarNote;
        private Label labelSidebarTitle;
        private Button btnThongKe;
        private Button btnChiTietHoaDon;
        private Button btnHoaDon;
        private Button btnKhachHang;
        private Button btnNhanVien;
        private Button btnNhaCungCap;
        private Button btnLoaiSanPham;
        private Button btnSanPham;
        private Panel panelHeader;
        private Button btnDangXuat;
        private Label lblQuyen;
        private Label labelQuyen;
        private Label lblHoTen;
        private Label labelNguoiDung;
        private Panel panelContent;
        private Panel panelWorkflow;
        private Label labelWorkflowText;
        private Label labelWorkflowTitle;
        private Panel panelWelcome;
        private Label labelWelcomeNote;
        private Label lblLoiChao;
    }
}
